services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: nestjs_backend
    command: sh -c 'npm run start:dev'
    env_file:
      - .env.dev
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=boilerplate
    ports:
      - '5439:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - '6377:6379'
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
