# Use official Node.js LTS image
FROM node:22

# Set working directory
WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# RUN npm install --include=optional sharp

# RUN npm install --os=linux --libc=musl --cpu=x64 sharp

# Copy source code
COPY . .

# Expose application port
EXPOSE 3000

CMD ["npm", "run", "start:dev"]